spring:
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

logging:
  level:
    wemade: debug

server:
  error:
    include-binding-errors: always
    include-message: always
    include-exception: false
    include-stacktrace: never
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


jwt:
  header: Authorization
  #echo 'jungyong-coding-test-spring-boot-wemade-secret-access-token-jungyong-coding-test-spring-boot-wemade-secret-access-token'|base64
  access-token-secret: anVuZ3lvbmctY29kaW5nLXRlc3Qtc3ByaW5nLWJvb3Qtd2VtYWRlLXNlY3JldC1hY2Nlc3MtdG9rZW4tanVuZ3lvbmctY29kaW5nLXRlc3Qtc3ByaW5nLWJvb3Qtd2VtYWRlLXNlY3JldC1hY2Nlc3MtdG9rZW4K
  #echo 'jungyong-coding-test-spring-boot-wemade-secret-refresh-token-jungyong-coding-test-spring-boot-wemade-secret-refresh-token'|base64
  refresh-token-secret: anVuZ3lvbmctY29kaW5nLXRlc3Qtc3ByaW5nLWJvb3Qtd2VtYWRlLXNlY3JldC1yZWZyZXNoLXRva2VuLWp1bmd5b25nLWNvZGluZy10ZXN0LXNwcmluZy1ib290LXdlbWFkZS1zZWNyZXQtcmVmcmVzaC10b2tlbgo=
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 259200

klaytn:
  rpc-url: https://public-node-api.klaytnapi.com/v1/cypress
